absl-py==1.0.0
appnope @ file:///opt/concourse/worker/volumes/live/4f734db2-9ca8-4d8b-5b29-6ca15b4b4772/volume/appnope_1606859466979/work
argcomplete @ file:///tmp/build/80754af9/argcomplete_1618920853202/work
astunparse==1.6.3
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
backports.entry-points-selectable==1.1.1
beautifulsoup4==4.10.0
blis==0.7.5
bookmarks-parser==0.1.3
bs4==0.0.1
CacheControl==0.12.10
cached-property==1.5.2
cachetools==5.0.0
cachy==0.3.0
catalogue==2.0.6
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.9
cleo==0.8.1
click==8.0.3
clikit==0.6.2
cobble==0.1.3
colorama==0.4.4
commonmark==0.9.1
crashtest==0.3.1
cryptography==36.0.1
cssselect==1.1.0
cymem==2.0.6
debugpy @ file:///opt/concourse/worker/volumes/live/32b11d06-4d64-4ec8-497a-cf4fc97343d2/volume/debugpy_1637091821874/work
decorator @ file:///tmp/build/80754af9/decorator_1632776554403/work
distlib==0.3.4
distro==1.6.0
en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.2.0/en_core_web_lg-3.2.0-py3-none-any.whl
en-core-web-md @ https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.2.0/en_core_web_md-3.2.0-py3-none-any.whl
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0-py3-none-any.whl
entrypoints==0.3
faiss-cpu==1.7.2
feedfinder2==0.0.4
feedparser==6.0.8
filelock==3.4.0
flatbuffers==1.12
gast==0.4.0
google-auth==2.5.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.43.0
h5py==3.6.0
html-to-json==2.0.0
html2text==2020.1.16
html5lib==1.1
huggingface-hub==0.4.0
idna==3.3
imageio==2.14.1
importlib-metadata @ file:///opt/concourse/worker/volumes/live/6e6ff5a0-f7a2-4c13-69e3-2158eeeea26b/volume/importlib-metadata_1638542890158/work
ipykernel @ file:///opt/concourse/worker/volumes/live/ee8433fe-cc9b-44e9-5a1b-fa2fa242a287/volume/ipykernel_1633545427588/work/dist/ipykernel-6.4.1-py3-none-any.whl
ipython @ file:///opt/concourse/worker/volumes/live/4f59a646-357b-46a9-5853-fe226d6346b8/volume/ipython_1635944180000/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
jedi @ file:///opt/concourse/worker/volumes/live/e0916850-3b97-4da2-5dee-49b0d9627cef/volume/jedi_1611333761589/work
jellyfish==0.8.9
jieba3k==0.35.1
Jinja2==3.0.3
joblib==1.1.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1637148478538/work
jupyter-core @ file:///opt/concourse/worker/volumes/live/118be231-668e-4924-6cae-07a558d8a92f/volume/jupyter_core_1636537052500/work
keras==2.7.0
Keras-Preprocessing==1.1.2
keybert==0.5.0
keyring==21.8.0
langcodes==3.3.0
leveldb==0.201
libclang==13.0.0
lockfile==0.12.2
lxml==4.7.1
mailbox==0.4
mammoth==1.4.18
Markdown==3.3.6
markdownify==0.10.1
MarkupSafe==2.0.1
matplotlib-inline @ file:///tmp/build/80754af9/matplotlib-inline_1628242447089/work
mkl-fft==1.3.1
mkl-random @ file:///opt/concourse/worker/volumes/live/133f1d0b-8fd8-4fa0-679e-7214401cbd75/volume/mkl_random_1626186083386/work
mkl-service==2.4.0
msgpack==1.0.3
murmurhash==1.0.6
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1613680548246/work
networkx==2.6.3
newspaper3k==0.2.8
nltk==3.6.5
numpy==1.21.5
oauthlib==3.2.0
onnx==1.10.2
onnxconverter-common==1.9.0
opt-einsum==3.3.0
packaging==20.9
pandas==1.3.5
parso @ file:///tmp/build/80754af9/parso_1617223946239/work
pastel==0.2.1
pathy==0.6.1
pdfminer.six==20211012
pdftotree==0.5.0
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleDB==0.9.2
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==8.4.0
pkginfo==1.8.2
platformdirs==2.4.0
plyvel==1.3.0
poetry==1.1.12
poetry-core==1.0.7
preshed==3.0.6
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1633440160888/work
protobuf==3.19.4
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pydantic==1.8.2
Pygments @ file:///tmp/build/80754af9/pygments_1629234116488/work
pylev==1.4.0
pyparsing==3.0.6
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
pytz==2021.3
PyWavelets==1.2.0
PyYAML==6.0
pyzmq @ file:///opt/concourse/worker/volumes/live/7dec6841-64b1-4d95-7226-ce37c6ca8915/volume/pyzmq_1638435000749/work
rake-nltk==1.0.6
readability-lxml==0.8.1
regex==2021.11.10
requests==2.26.0
requests-file==1.5.1
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
rich==11.1.0
rsa==4.8
sacremoses==0.0.47
scikit-image==0.19.1
scikit-learn==1.0.2
scipy==1.7.3
segtok==1.5.11
selectivesearch==0.4
sentence-transformers==2.2.0
sentencepiece==0.1.96
sgmllib3k==1.0.0
shellingham==1.4.0
six @ file:///tmp/build/80754af9/six_1623709665295/work
sklearn==0.0
smart-open==5.2.1
soupsieve==2.3.1
spacy==3.2.1
spacy-legacy==3.0.8
spacy-loggers==1.0.1
srsly==2.4.2
tabula-py==2.3.0
tabulate==0.8.9
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.7.0
tensorflow-estimator==2.7.0
tensorflow-io-gcs-filesystem==0.23.1
termcolor==1.1.0
tf2onnx==1.9.3
thinc==8.0.13
threadpoolctl==3.0.0
tifffile==2021.11.2
tinysegmenter==0.3
tldextract==3.1.2
tokenizers==0.11.4
tomlkit==0.8.0
torch==1.10.2
torchvision==0.11.3
tornado @ file:///opt/concourse/worker/volumes/live/d531d395-893c-4ca1-6a5f-717b318eb08c/volume/tornado_1606942307627/work
tqdm==4.62.3
traitlets @ file:///tmp/build/80754af9/traitlets_1636710298902/work
transformers==4.16.1
typer==0.4.0
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1631814937681/work
urllib3==1.26.7
validators==0.18.2
virtualenv==20.10.0
Wand==0.6.7
wasabi==0.9.0
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webencodings==0.5.1
Werkzeug==2.0.2
wikipedia==1.4.0
wordwise==0.0.4
wrapt==1.13.3
xmltodict==0.12.0
xmltojson==0.2.0
yake==0.4.8
zipp @ file:///tmp/build/80754af9/zipp_1633618647012/work
